//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated by a tool.
//     Runtime Version:4.0.30319.42000
//
//     Changes to this file may cause incorrect behavior and will be lost if
//     the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace nilnul._stat_._TEST_.nilnul0.num.real.ext.func_.unary_.erf._test {
    using System;
    
    
    /// <summary>
    ///   A strongly-typed resource class, for looking up localized strings, etc.
    /// </summary>
    // This class was auto-generated by the StronglyTypedResourceBuilder
    // class via a tool like ResGen or Visual Studio.
    // To add or remove a member, edit your .ResX file then rerun ResGen
    // with the /str option, or rebuild your VS project.
    [global::System.CodeDom.Compiler.GeneratedCodeAttribute("System.Resources.Tools.StronglyTypedResourceBuilder", "17.0.0.0")]
    [global::System.Diagnostics.DebuggerNonUserCodeAttribute()]
    [global::System.Runtime.CompilerServices.CompilerGeneratedAttribute()]
    internal class Resource1 {
        
        private static global::System.Resources.ResourceManager resourceMan;
        
        private static global::System.Globalization.CultureInfo resourceCulture;
        
        [global::System.Diagnostics.CodeAnalysis.SuppressMessageAttribute("Microsoft.Performance", "CA1811:AvoidUncalledPrivateCode")]
        internal Resource1() {
        }
        
        /// <summary>
        ///   Returns the cached ResourceManager instance used by this class.
        /// </summary>
        [global::System.ComponentModel.EditorBrowsableAttribute(global::System.ComponentModel.EditorBrowsableState.Advanced)]
        internal static global::System.Resources.ResourceManager ResourceManager {
            get {
                if (object.ReferenceEquals(resourceMan, null)) {
                    global::System.Resources.ResourceManager temp = new global::System.Resources.ResourceManager("nilnul._stat_._TEST_.nilnul0.num.real.ext.func_.unary_.erf._test.Resource1", typeof(Resource1).Assembly);
                    resourceMan = temp;
                }
                return resourceMan;
            }
        }
        
        /// <summary>
        ///   Overrides the current thread's CurrentUICulture property for all
        ///   resource lookups using this strongly typed resource class.
        /// </summary>
        [global::System.ComponentModel.EditorBrowsableAttribute(global::System.ComponentModel.EditorBrowsableState.Advanced)]
        internal static global::System.Globalization.CultureInfo Culture {
            get {
                return resourceCulture;
            }
            set {
                resourceCulture = value;
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to x,erf, erfc
        ///0,0,1
        ///0.02,0.022564575,0.977435425
        ///0.04,0.045111106,0.954888894
        ///0.06,0.067621594,0.932378406
        ///0.08,0.090078126,0.909921874
        ///0.1,0.112462916,0.887537084
        ///0.2,0.222702589,0.777297411
        ///0.3,0.328626759,0.671373241
        ///0.4,0.428392355,0.571607645
        ///0.5,0.520499878,0.479500122
        ///0.6,0.603856091,0.396143909
        ///0.7,0.677801194,0.322198806
        ///0.8,0.742100965,0.257899035
        ///0.9,0.796908212,0.203091788
        ///1,0.842700793,0.157299207
        ///1.1,0.88020507,0.11979493
        ///1.2,0.910313978,0.089686022
        ///1.3,0.934007945,0.065992055
        /// [rest of string was truncated]&quot;;.
        /// </summary>
        internal static string erf9erfc {
            get {
                return ResourceManager.GetString("erf9erfc", resourceCulture);
            }
        }
    }
}
